#!/usr/bin/env bash
# Aggregate every udfs/**/*.sql and preprocessor/**/*.sql into a single
# dist/mariadb-compat.sql that can be loaded via `exaplus -f` or `python
# install.py`. install.py installs all scripts; exaplus installs the schema,
# every scalar UDF, and the production MARIA_PREPROCESSOR — see notes below
# for why MARIA_PREPROCESSOR_DEBUG is install.py-only.
set -euo pipefail

cd "$(dirname "$0")"

OUT="dist/mariadb-compat.sql"
VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo 'dev')"

mkdir -p dist

{
    echo "-- exasol-mariadb-compat ${VERSION}"
    echo "-- Auto-generated by build.sh from udfs/ and preprocessor/ — DO NOT EDIT."
    echo "-- Install:  exaplus -f dist/mariadb-compat.sql   (installs 8 of 9 scripts)"
    echo "--     or:   python install.py ...                (installs all 9 — recommended)"
    echo "--"
    echo "-- exaplus 25.2.6 has a client-side parser bug: after the FIRST"
    echo "-- --/ ... / PREPROCESSOR block, subsequent --/ markers no longer enter"
    echo "-- script-body mode and the next script's body is dropped. This bundle"
    echo "-- orders the production MARIA_PREPROCESSOR before MARIA_PREPROCESSOR_DEBUG"
    echo "-- so production survives the exaplus path; DEBUG is dev-only and"
    echo "-- install.py installs both reliably."
    echo
    echo "CREATE SCHEMA IF NOT EXISTS UTIL;"
    echo

    # UDFs first (referenced by the preprocessor), then preprocessor — sorted
    # bytewise (LC_ALL=C) so `maria_preprocessor.sql` (`.` < `_`) precedes
    # `maria_preprocessor_debug.sql`. Each script body is wrapped in `--/` ...
    # `/` block markers so exaplus enters script-body mode for the embedded
    # Python — without them, exaplus tries to SQL-parse lines like
    # `# reference); ...` and fails with "more then one SQL statement". `--/`
    # is a SQL line-comment to anything else, so tools that don't honour the
    # convention (pyexasol direct execute) ignore it cleanly.
    {
        LC_ALL=C find udfs -name '*.sql' -print0 2>/dev/null | LC_ALL=C sort -z
        LC_ALL=C find preprocessor -name '*.sql' -print0 2>/dev/null | LC_ALL=C sort -z
    } | while IFS= read -r -d '' f; do
        rel="${f}"
        echo "-- === ${rel} ==="
        echo "--/"
        # Emit the body verbatim — never touch internal `;` or `/`. Python
        # comments inside the script can legitimately contain `;` (and even
        # `/` mid-line); rewriting them confuses exaplus's block-mode parser
        # and causes the install to silently drop the script. Convention is
        # that source files do NOT have a trailing `;` or `/` (see README),
        # so the trailing `/` we emit below is the only block terminator.
        cat "$f"
        echo "/"
        echo
    done
} > "${OUT}"

lines=$(wc -l < "${OUT}")
echo "Built ${OUT} (${lines} lines, ${VERSION})"
