#!/usr/bin/env bash
# Aggregate every udfs/**/*.sql and preprocessor/**/*.sql into a single
# dist/mariadb-compat.sql that can be loaded via `exaplus -f` or `python
# install.py`. install.py installs all scripts; exaplus installs the schema,
# every scalar UDF, and the production MARIA_PREPROCESSOR — see notes below
# for why MARIA_PREPROCESSOR_DEBUG is install.py-only.
set -euo pipefail

cd "$(dirname "$0")"

OUT="dist/mariadb-compat.sql"
VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo 'dev')"

mkdir -p dist

{
    echo "-- exasol-mariadb-compat ${VERSION}"
    echo "-- Auto-generated by build.sh from udfs/ and preprocessor/ — DO NOT EDIT."
    echo "-- Install:  exaplus -f dist/mariadb-compat.sql"
    echo "--     or:   python install.py ..."
    echo "--"
    echo "-- Import directly into Exasol via an Exasol connector (exaplus, the"
    echo "-- pyexasol-based install.py, or any Exasol driver) — NOT through MaxScale."
    echo "-- The --/ ... / script-block markers and CREATE SCRIPT bodies below are"
    echo "-- exaplus/Exasol-native and do not survive a MariaDB client + preprocessor."
    echo "--"
    echo "-- exaplus 25.2.6 does not enter script-body mode for CREATE PREPROCESSOR"
    echo "-- SCRIPT (works fine for SCALAR SCRIPT). The bundle therefore wraps"
    echo "-- SCALAR UDFs in --/ ... / blocks and emits PREPROCESSOR scripts with"
    echo "-- a bare trailing \`;\` — preprocessor source files must keep \`;\` out of"
    echo "-- their Python comments so the bare-\`;\` form has a single statement"
    echo "-- terminator at the very end."
    echo
    echo "CREATE SCHEMA IF NOT EXISTS UTIL;"
    echo

    # UDFs first (referenced by the preprocessor), then preprocessor — sorted
    # bytewise (LC_ALL=C) so `maria_preprocessor.sql` (`.` < `_`) precedes
    # `maria_preprocessor_debug.sql`. Each script body is wrapped in `--/` ...
    # `/` block markers so exaplus enters script-body mode for the embedded
    # Python — without them, exaplus tries to SQL-parse lines like
    # `# reference); ...` and fails with "more then one SQL statement". `--/`
    # is a SQL line-comment to anything else, so tools that don't honour the
    # convention (pyexasol direct execute) ignore it cleanly.
    # SCALAR UDFs use --/ ... / block markers (exaplus enters script-body mode
    # for SCALAR SCRIPT). PREPROCESSOR SCRIPT does NOT trigger block mode in
    # exaplus 25.2.6, so its body must terminate with a bare `;` and contain
    # no `;` anywhere else — comments are kept `;`-free in source by convention.
    {
        LC_ALL=C find udfs -name '*.sql' -print0 2>/dev/null | LC_ALL=C sort -z
    } | while IFS= read -r -d '' f; do
        echo "-- === ${f} ==="
        echo "--/"
        cat "$f"
        echo "/"
        echo
    done

    {
        LC_ALL=C find preprocessor -name '*.sql' -print0 2>/dev/null | LC_ALL=C sort -z
    } | while IFS= read -r -d '' f; do
        echo "-- === ${f} ==="
        # exaplus parses preprocessor bodies as SQL (no script-body mode), so
        # any character its tokenizer treats specially — `;`, unbalanced `'`,
        # etc. — derails the install. Drop comment-only lines (those whose
        # first non-whitespace char is `#`) so apostrophes in human prose
        # ("node's", "can't") never reach exaplus. The catalog SCRIPT_TEXT
        # ends up comment-stripped; install.py (pyexasol) ships full source.
        sed -E '/^[[:space:]]*#/d' "$f"
        echo ";"
        echo
    done
} > "${OUT}"

lines=$(wc -l < "${OUT}")
echo "Built ${OUT} (${lines} lines, ${VERSION})"
